import { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/router";
const Top: NextPage = () => {
  // const { currentUser, login, logout } = useAuth();
  const { currentUser, login, logout } = useAuth();
  const router = useRouter();
  const handleLoginButton = () => {
    login && login();
  };
  const handleLogoutButton = () => {
    if (!logout) return;
    logout();
  };
  return (
    <div>
      <Head>
        <title>top</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>/</h1>
        {currentUser ? (
          <div>
            <h2>ログインしています.</h2>
            <button onClick={handleLogoutButton}>ログアウト</button>
            {!!currentUser.photoURL && (
              <Image
                src={currentUser.photoURL}
                alt=""
                width="100"
                height="100"
              />
            )}
            <Link href="/home">
              <a>HOME</a>
            </Link>
            <div></div>
            <Link href="/room/m6s2o6brCyEsXBRxhS3M">
              <a>m6s2o6brCyEsXBRxhS3M</a>
            </Link>
            <div></div>
            <Link href="/room/list">
              <a>room/list</a>
            </Link>
          </div>
        ) : (
          <button onClick={handleLoginButton}>signin</button>
        )}
      </main>

      <footer></footer>
    </div>
  );
};

export default Top;
